export const ACTION = {
	START_TEST: "START_TEST",
	SET_TEST_ID: "SET_TEST_ID",
	SET_USER_ANSWER:"SET_USER_ANSWER",
	SET_TEST_LENGTH: "SET_TEST_LENGTH",
	RESET_USER_ANSWERS: "RESET_USER_ANSWERS",
	GET_RESULTS: "GET_RESULTS",
	GET_TEST: "GET_TEST",
	EDIT_QUESTION: "EDIT_QUESTION",
	ADD_QUESTION: "ADD_QUESTION",
	DELETE_QUESTION: "DELETE_QUESTION"
}
