export * from './MainPage'
export * from './QuizPage'
export * from './CreateOrEditPage'
export * from './LoginPage'
export * from './RegisterPage'
export * from './ProfilePage'
export * from './UserTestsPage'
export * from './TestPage'